export type AuthStackParamList = {
  Splash: undefined;
  Welcome: undefined;
  Login: undefined;
  MobileNumber: { intent: 'login' | 'create-account' };
  OtpVerification: { mobileNumber: string; intent: 'login' | 'create-account' };
  AccountNotFound: { mobileNumber: string };
  CreateAccount: { mobileNumber: string; verifiedPhoneToken: string };
  ResetPassword: { resetToken: string };

  BusinessType: undefined;
  BusinessInfo: undefined;
  OwnerInfo: undefined;
  StoreInfo: undefined;
  StoreLocation: undefined;
  GSTDetails: undefined;
  PANVerification: undefined;
  BusinessProof: undefined;
  BankDetails: undefined;

  KYCReview: undefined;
  VendorAgreement: undefined;
  KYCSubmission: undefined;
  KYCPending: undefined;
  KYCApproved: undefined;
  KYCRejected: { rejectionReason?: string } | undefined;
  RegistrationComplete: undefined;

  StoreSetupIntro: undefined;
  StoreProfile: undefined;
  StoreLogoUpload: undefined;
  StoreCoverImage: undefined;
  StoreAddress: undefined;
  StoreLocationConfirm: undefined;
  OperatingHours: undefined;
  WeeklySchedule: undefined;
  HolidayClosure: undefined;
  HolidayForm: { holidayId?: string } | undefined;
  DeliverySettings: undefined;
  ServiceAvailability: undefined;
  StoreStatus: undefined;
  TempClosure: undefined;
  ClosureConfirmation: undefined;
  StoreSetupComplete: undefined;

  Dashboard: undefined;

  ProductCatalog: undefined;
  ProductSearch: undefined;
  ProductFilters: undefined;
  CategoryBrowse: undefined;
  CategoryProductListing: { categoryId: string };
  ProductDetails: { productId: string };

  AddProduct: undefined;
  ProductBasicInfo: undefined;
  BrandPicker: undefined;
  ProductImages: undefined;
  ProductCategoryStep: undefined;
  ProductSubcategoryStep: { categoryId: string };
  ProductDescriptionStep: undefined;
  PackSizeVariant: undefined;
  ProductMRP: undefined;
  ProductSellingPrice: undefined;
  ProductDiscount: undefined;
  ProductTaxInfo: undefined;
  ProductSKU: undefined;
  ProductBarcode: undefined;
  ProductStockQuantity: undefined;
  ProductAvailability: undefined;
  ReviewProduct: undefined;
  PublishProduct: undefined;
  PublishSuccess: undefined;

  EditProduct: { productId: string };
  EditInformation: { productId: string };
  EditImages: { productId: string };
  EditPrice: { productId: string };
  EditStock: { productId: string };
  ActivateProduct: { productId: string };
  DeactivateProduct: { productId: string };
  DeleteProduct: { productId: string };
  DeleteConfirmation: { productName: string; sku: string };

  InventoryOverview: undefined;
  InStock: undefined;
  LowStock: undefined;
  OutOfStock: undefined;
  Unavailable: undefined;
  InventorySearch: undefined;
  InventoryFilter: undefined;
  ProductStockDetails: { productId: string };
  UpdateQuantity: { productId: string };
  BulkUpdate: { productIds?: string[] };
  StockAdjustment: { productId?: string };
  InventoryHistory: { productId?: string };
  LowStockAlert: undefined;
  OOSConfirmation: { productId: string };

  OrdersList: undefined;
  NewOrders: undefined;
  PreparingOrders: undefined;
  QualityCheckOrders: undefined;
  PackingOrders: undefined;
  ReadyForDispatchOrders: undefined;
  DispatchedOrders: undefined;
  CompletedOrders: undefined;
  CancelledOrders: undefined;
  FailedOrders: undefined;
  OrderDetails: { orderId: string };

  NewOrderReceived: { orderId: string };
  AcceptOrderConfirm: { orderId: string };
  RejectOrderWarning: { orderId: string };
  RejectReason: { orderId: string };
  RejectOrderConfirmation: { orderId: string; reasonLabel: string };
  InventoryCheck: { orderId: string };
  ProductPicking: { orderId: string };
  ItemAvailability: { orderId: string };
  MissingItemDecision: { orderId: string; itemName: string; itemPrice: number; itemQty: number };
  ReplaceItem: { orderId: string; itemName: string; itemPrice: number; itemQty: number; source: 'missing' | 'qc' };
  RemoveItem: { orderId: string; itemName: string; itemPrice: number; itemQty: number; source: 'missing' | 'qc' };
  OrderUpdated: {
    orderId: string;
    resolution: 'replaced' | 'removed';
    itemName: string;
    itemPrice: number;
    source: 'missing' | 'qc';
  };
  QualityCheckFlow: { orderId: string };
  QCFailedDecision: { orderId: string; itemName: string; itemPrice: number; itemQty: number };
  QCPassed: { orderId: string };
  PackingStart: { orderId: string };
  PackingInProgress: { orderId: string };
  PackingComplete: { orderId: string };
  ReadyForDispatchConfirm: { orderId: string };
  DispatchQueue: { orderId: string };
  PartnerAssigned: { orderId: string };
  HandoverChecklist: { orderId: string };
  HandoverConfirmation: { orderId: string };
  OrderDispatched: { orderId: string };
  OrderDelivered: { orderId: string };

  CancelledOrderDetails: { orderId: string };
  VendorCancelOrder: { orderId: string };
  CancellationReason: { orderId: string };
  CancellationConfirmation: { orderId: string; reasonLabel: string };
  FailedOrderDetails: { orderId: string };
  OrderActionError: { orderId: string; actionLabel: string };
  RetryingAction: { orderId: string; actionLabel: string };
  ActionRecovered: { orderId: string; actionLabel: string };

  PricingOverview: undefined;
  CategoryPricingList: { categoryId?: string; categoryName?: string };
  ProductPricingDetail: { productId: string };
  PricingCombinedEdit: { productId: string };
  MRPEditor: { productId: string };
  SellingPriceEditor: { productId: string };
  DiscountEditor: { productId: string };
  TaxEditor: { productId: string };
  PriceReview: {
    productId: string;
    pendingMrp?: number;
    pendingSellingPrice?: number;
    changes: { field: string; from: string; to: string }[];
  };
  PriceUpdated: { productId: string; headline: string; message: string };
  PriceUpdateError: {
    productId: string;
    pendingMrp?: number;
    pendingSellingPrice?: number;
    changes: { field: string; from: string; to: string }[];
    headline: string;
    message: string;
    errorCode: string;
    errorField: string;
  };

  OffersOverview: undefined;
  ActiveOffers: undefined;
  ScheduledOffers: undefined;
  ExpiredOffers: undefined;
  OfferDetail: { offerId: string };
  CreateOffer: { offerId?: string };
  SelectOfferProducts: undefined;
  OfferConditions: undefined;
  OfferDiscountValue: undefined;
  OfferStartDate: undefined;
  OfferEndDate: undefined;
  OfferReview: undefined;
  PublishOffer: undefined;
  OfferPublished: { offerId: string };
  PauseOffer: { offerId: string };
  DeleteOffer: { offerId: string };

  PaymentsOverview: undefined;
  TotalSales: undefined;
  PendingSettlement: undefined;
  PaidSettlement: undefined;
  Deductions: undefined;
  SettlementDetails: { settlementId: string };
  Commission: undefined;
  Taxes: undefined;
  Adjustments: undefined;
  NetSettlement: { settlementId: string };
  SettlementHistory: undefined;
  TransactionDetails: { settlementId: string };
  Invoice: { settlementId: string };
  ViewInvoice: { settlementId: string };
  DownloadInvoice: { settlementId: string };
  PaymentError: { settlementId: string };
  SettlementIssue: { settlementId: string };

  AnalyticsOverview: undefined;
  SalesAnalytics: undefined;
  OrdersAnalytics: undefined;
  RevenueAnalytics: undefined;
  AverageOrderValue: undefined;
  BestSellingProducts: undefined;
  LowPerformingProducts: undefined;
  CancellationAnalytics: undefined;
  InventoryPerformance: undefined;
  SettlementSummary: undefined;

  Notifications: undefined;
  NewOrderNotification: { notificationId: string };
  OrderCancellationNotification: { notificationId: string };
  LowStockNotification: { notificationId: string };
  OutOfStockNotification: { notificationId: string };
  PaymentNotification: { notificationId: string };
  SettlementNotification: { notificationId: string };
  ProductApprovalNotification: { notificationId: string };
  KYCStatusNotification: { notificationId: string };
  StoreStatusNotification: { notificationId: string };
  SystemAlertNotification: { notificationId: string };
  AnnouncementNotification: { notificationId: string };
  NotificationDetail: { notificationId: string };
  ClearNotifications: undefined;

  HelpSupport: undefined;
  SupportCategories: undefined;
  SelectIssue: { categoryId: string };
  IssueDetails: { categoryId: string; issueId: string };
  UploadEvidence: undefined;
  PreviewEvidence: undefined;
  SubmitTicket: undefined;
  TicketCreated: { ticketId: string };
  TicketDetails: { ticketId: string };
  TicketStatus: undefined;
  SupportResponse: { ticketId: string };
  TicketResolved: { ticketId: string };
  ReopenTicket: { ticketId: string };
  EscalateTicket: { ticketId: string };
  TicketClosed: { ticketId: string };

  DisputeCustomerIssue: { disputeId: string };
  DisputeIssueDetails: { disputeId: string };
  DisputeVendorReview: { disputeId: string };
  DisputeAcceptIssue: { disputeId: string };
  DisputeIssueDispute: { disputeId: string };
  DisputeUploadEvidence: { disputeId: string };
  DisputeSubmit: { disputeId: string };
  DisputeSupportReview: { disputeId: string };
  DisputeDecision: { disputeId: string };
  DisputeSettlementAdjustment: { disputeId: string };
  DisputeResolved: { disputeId: string };

  Profile: undefined;
  ProfileVendorInfo: undefined;
  ProfileEditVendorInfo: undefined;
  ProfileOwnerInfo: undefined;
  ProfileEditOwnerInfo: undefined;
  ProfileStoreInfo: undefined;
  ProfileEditStoreInfo: undefined;
  ProfileAddresses: undefined;
  ProfileAddAddress: undefined;
  ProfileAddressDetails: { addressId: string };
  ProfileDocuments: undefined;
  ProfileAddDocument: undefined;
  ProfileDocumentStatus: { documentId: string };
  ProfileReplaceDocument: { documentId: string };
  ProfileBankDetails: undefined;
  ProfileEditBankDetails: undefined;
  ProfileNotificationSettings: undefined;
  ProfileSecurity: undefined;

  SecurityChangeMobileNumber: undefined;
  SecurityChangeMobileOtp: { newMobileNumber: string };
  SecurityChangePin: undefined;
  SecurityActiveSessions: undefined;
  SecurityLoginHistory: undefined;
  SecurityLogout: undefined;
  SecurityLogoutConfirmation: undefined;
  SecurityDeleteAccountConfirm: undefined;

  PolicyTerms: undefined;
  PolicyPrivacy: undefined;
  PolicyVendorAgreement: undefined;
  PolicyCancellation: undefined;
  PolicySettlement: undefined;
};
